apiVersion: v1
kind: Template
labels:
  template: rhscl-http-template
metadata:
  annotations:
    description: HTTP
    iconClass: icon-shadowman
    tags: rhel,apache,http
  creationTimestamp: null
  name: rhscl-http
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: rhscl-http-ose
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in the application image
    name: ${HTTP_SERVICE_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
    name: rhscl-http-ose
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: rhscl-http-ose:latest
    source:
      contextDir: ${HTTP_OSE_DOCKERFILE_CONTEXT_DIR}
      git:
        uri: ${HTTP_OSE_DOCKERFILE_REPOSITORY_URL}
      type: Git
    strategy:
      dockerStrategy:
      type: Docker
    triggers:
    - github:
        secret: ${HTTP_OSE_DOCKERFILE_GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: Generic
      generic:
        secret: ${HTTP_OSE_DOCKERFILE_GENERIC_WEBHOOK_SECRET}
    - type: ConfigChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
    name: ${HTTP_SERVICE_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${HTTP_SERVICE_NAME}:latest
    source:
      contextDir: ${HTTP_CONFIG_CONTEXT_DIR}
      git:
        ref: ${HTTP_CONFIG_REPOSITORY_REF}
        uri: ${HTTP_CONFIG_REPOSITORY_URL}
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: HTTPD_CONFIGURATION_PATH
          value: ${HTTPD_CONFIGURATION_PATH}
        from:
          kind: ImageStreamTag
          name: rhscl-http-ose:latest
      type: Source
    triggers:
    - type: ImageChange
    - github:
        secret: ${HTTP_CONFIG_GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - type: Generic
      generic:
        secret: ${HTTP_CONFIG_GENERIC_WEBHOOK_SECRET}
parameters:
- description: The name of the HTTP service
  displayName: HTTP Service Name
  name: HTTP_SERVICE_NAME
  value: http
  required: true
- description: The URL of the repository with your application source code.
  displayName: HTTP OSE Git Repository URL
  name: HTTP_OSE_DOCKERFILE_REPOSITORY_URL
  required: true
  value: https://github.com/kevensen/rhscl-http-ose.git
- description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.
  displayName: HTTP OSE Git Reference
  name: HTTP_OSE_DOCKERFILE_REPOSITORY_REF
  required: true
  value: master
- description: Set this to the relative path to your project if it is not in the root
    of your repository.
  displayName: HTTP OSE Context Directory
  name: HTTP_OSE_DOCKERFILE_CONTEXT_DIR
  required: true
  value: /
- description: A secret string used to configure the GitHub webhook for the HTTP OSE repository.
  displayName: HTTP OSE GitHub Webhook Secret
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: HTTP_OSE_DOCKERFILE_GITHUB_WEBHOOK_SECRET
- description: A secret string used to configure the generic webhook for the HTTP OSE repository.
  displayName: HTTP OSE Generic Webhook Secret
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: HTTP_OSE_DOCKERFILE_GENERIC_WEBHOOK_SECRET
- description: The path containing the HTTP configuration files
  displayName: HTTP Configuration Path
  name: HTTPD_CONFIGURATION_PATH
  value: /opt/app-root/etc/httpd.d
  required: true
- description: The URL of the repository with the Apache configuration.
  displayName: Git Repository URL
  name: HTTP_CONFIG_REPOSITORY_URL
  required: true
- description: Set this to a branch name, tag or other ref of your repository if you
    are not using the default branch.
  displayName: Git Reference
  name: HTTP_CONFIG_REPOSITORY_REF
  required: true
  value: master
- description: Set this to the relative path to your project if it is not in the root
    of your repository.
  displayName: Context Directory
  name: HTTP_CONFIG_CONTEXT_DIR
  required: true
  value: /
- description: The exposed hostname that will route to the CakePHP service, if left
    blank a value will be defaulted.
  displayName: Application Hostname
  name: APPLICATION_DOMAIN
- description: A secret string used to configure the GitHub webhook.
  displayName: GitHub Webhook Secret
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: HTTP_CONFIG_GITHUB_WEBHOOK_SECRET
- description: A secret string used to configure the generic webhook.
  displayName: Generic Webhook Secret
  from: '[a-zA-Z0-9]{40}'
  generate: expression
  name: HTTP_CONFIG_GENERIC_WEBHOOK_SECRET
